/* analyzer.h
  Assignment #5
  Created by Gyouk Chu on 02/12/2021
  Last Updated on 06/12/2021
*/

#include "dynarray.h"
#include "token.h"
#ifndef ANALYZER_INCLUDED
#define ANALYZER_INCLUDED

/* Lexically Analyze pcLine and make oTokens */
int lexLine(const char *pcLine, DynArray_T oTokens);

/* Syntatically Analyze oTokens generated by lexLine */
int synLine(DynArray_T oTokens);

#endif